### ISSUE TITLE
Package should support URL Signing

### ISSUE THREAD

**Issue by jackwh** [mastani/laravel-google-static-map#1]
Thanks for releasing this package!

To support security best practices and exceed certain usage restrictions, the package should allow for generating signed URLs: https://developers.google.com/maps/documentation/maps-static/get-api-key?hl=en_GB#detailed-guides-to-generating-a-digital-signature

**Comment by mastani** [comment]
Thank you for your suggestion, I add this feature. See ebcf3c52653846fcb2512099c210ef109c749497.
