### ISSUE TITLE
Support for Laravel 11

### ISSUE THREAD

**Issue by geofftech** [mastani/laravel-google-static-map#16]
The package seems works perfectly in Laravel 11. It just needs support in `composer.json`.

```
    "require": {
        "illuminate/contracts": "5.*|6.*|7.*|8.*|^9.0|^10.0|^11",
        "illuminate/support": "5.*|6.*|7.*|8.*|^9.0|^10.0|^11"
    },
```

**Comment by geofftech** [comment]
I just went to add a PR and noticed there is already one there from Laravel Shift. With detailed instructions!!

**Comment by cheesegrits** [comment]
@mastani another request to please update this to Laravel 11

**Comment by mastani** [comment]
Thank you for your comments. I apologize for being late in merging this request. I have now made a new release with this PR.
