### ISSUE TITLE
API Secret is countable?

### ISSUE THREAD

**Issue by theblindfrog** [mastani/laravel-google-static-map#2]
When a API Secret is passed to the setter, should it be a string or an array?

https://github.com/mastani/laravel-google-static-map/blob/ebcf3c52653846fcb2512099c210ef109c749497/src/GoogleStaticMap.php#L248-L249

Shouldn't this ☝️ check `strlen` rather than `count`? 

Relates to #1

**Comment by mastani** [comment]
Ah, You are right, my bad.
I fix it now. Thank you.

**Comment by theblindfrog** [comment]
Thanks @mastani! Are you able to tag a new release to packagist too?

**Comment by mastani** [comment]
@theblindfrog Done.
