### ISSUE TITLE
Laravel v6.0 Support

### ISSUE THREAD

**Issue by jackwh** [mastani/laravel-google-static-map#3]
It's not possible to install this package on a Laravel v6.0 project, as the Composer dependencies require `"illuminate/contracts": "5.*"` and `"illuminate/support": "5.*"`.

**Comment by mastani** [comment]
Thanks, fixed in 0f2b0c3eb6b091708f4c42487311932c99943068

**Comment by anroots** [comment]
Hey, could you also create a new Release where this change is included? Currently, I need to specify `dev-master` as a Composer version with Larave 6, because the last stable release doesn't include 0f2b0c3.

**Comment by mastani** [comment]
@anroots Thanks for reminding me, just did.
