### ISSUE TITLE
The Google Maps Platform server rejected your request. The provided API key is invalid.

### ISSUE THREAD

**Issue by faizalmuzakki** [mastani/laravel-google-static-map#5]
https://maps.googleapis.com/maps/api/staticmap?key={myapikey}¢er=Tehran&zoom=14&scale=1&size=600x600&maptype=roadmap&format=jpg&visual_refresh=true&markers=size:tiny%7Ccolor:red%7Clabel:1%7CTehran&markers=size:tiny%7Ccolor:red%7Clabel:1%7C35.6907488,51.3919293

why?

**Comment by mastani** [comment]
You have to provide a valid API key in order to get it work. See https://developers.google.com/maps/documentation/maps-static/get-api-key
